### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by brinsleyparagao** [teddysun/lamp#114]
When i try create a new vhost i taked this error msg:

```
Traceback (most recent call last):
  File "/tmp/tmp.cDHfGIcqzg/pipstrap.py", line 177, in <module>
    exit(main())
  File "/tmp/tmp.cDHfGIcqzg/pipstrap.py", line 158, in main
    for path, digest in PACKAGES]
  File "/tmp/tmp.cDHfGIcqzg/pipstrap.py", line 118, in hashed_download
    response = opener(using_https=parsed_url.scheme == 'https').open(url)
  File "/usr/lib64/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib64/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>
Error: Create Let's Encrypt SSL Certificate failed.
```

**Comment by teddysun** [comment]
Maybe you need to update package: nss
`yum install -y nss`
or
`apt-get install -y libnss3`

**Comment by AlekseiiShevchuk** [comment]
> Maybe you need to update package: nss
> `yum install -y nss`
> or
> `apt-get install -y libnss3`

it does not help
have the same error on Ubuntu 18 latest

**Comment by AlekseiiShevchuk** [comment]
need to run command
export PYTHONHTTPSVERIFY=0

**Comment by domainoverflow** [comment]
I am having the exact same problem ... ubuntu 18.04 and export PYTHON does not work nor does fix it - nor does apt-get install -y libnss3 ... anyone any ideas ? thanks.
