### ISSUE TITLE
SSL cert issuance (lamp add) not working Ubuntu 18.04

### ISSUE THREAD

**Issue by domainoverflow** [teddysun/lamp#117]
Ubuntu 18.04 .. when doing lamp add ... and then install SSL cert .. 

-Exporting PYTHONSSLCHECK does not work 
-Installing libnss3 does not fix it. 

any ideas ? thanks.

Traceback (most recent call last):
  File "/tmp/tmp.10IoxU308V/pipstrap.py", line 177, in <module>
    exit(main())
  File "/tmp/tmp.10IoxU308V/pipstrap.py", line 158, in main
    for path, digest in PACKAGES]
  File "/tmp/tmp.10IoxU308V/pipstrap.py", line 118, in hashed_download
    response = opener(using_https=parsed_url.scheme == 'https').open(url)
  File "/usr/lib64/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib64/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)>
Error: Create Let's Encrypt SSL Certificate failed.

**Comment by domainoverflow** [comment]
PS: To get around this ... install the shell script client for acme (  https://github.com/Neilpang/acme.sh ). 
1) sudo ./acme.sh --issue -d yourdomain.com -w /data/www/yourdomainrootPath 
2) write down the path location of both the cert and the key
3) lamp add yourdomain.com ... when it prompts "Install SSL Cert Y/N" - reply Yes
3.1) But instead choose the option to install your own certs 
3.2) Type in the location of both cert and key ( from #2 above ) 
4) LAMP's last question will be Force SSL Y/N ? That depends on you .. if Y a .htaccess will be created, it works but it erases the referrer .. 

It worked on Ubuntu 18.04

**Comment by Sippan-66** [comment]
Hi i get this also and have  try domainoverflow  above solution but dont work ....and i use also Ubuntu 18.04

WARNING: unable to check for updates.
Creating virtual environment...
Installing Python packages...
Traceback (most recent call last):
  File "/tmp/tmp.cLWZEydYGS/pipstrap.py", line 177, in <module>
    sys.exit(main())
  File "/tmp/tmp.cLWZEydYGS/pipstrap.py", line 158, in main
    for path, digest in PACKAGES]
  File "/tmp/tmp.cLWZEydYGS/pipstrap.py", line 117, in hashed_download
    response = opener(using_https=parsed_url.scheme == 'https').open(url)
  File "/usr/lib64/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib64/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)>
Error: Create Let's Encrypt SSL Certificate failed.
root@webserver:~/lamp#
