### ISSUE TITLE
Certbot: Failed authorization procedure

### ISSUE THREAD

**Issue by jazzi** [teddysun/lamp#82]
Hi, I failed to get the Let's Encrypt SSL certificate on Aliyun ECS, Debian 9.4, hereby the errors:

> Failed authorization procedure. gotea.com (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://gotea.com/.well-known/acme-challenge/iEhg8HiyYCpUf8ZYNMzGWBlmJIbomT0d8ncOU1E0o3M: Connection reset by peer

The Ping shows the DNS and IP is right.

**Comment by jazzi** [comment]
I resolved it. it's about the firewall.

`# systemctl status urf`

> ufw.service - Uncomplicated firewall
>    Loaded: loaded (/lib/systemd/system/ufw.service; enabled; vendor preset: enab
>    Active: active (exited) since Sun 2018-07-15 06:00:42 CST; 2 days ago
>  Main PID: 239 (code=exited, status=0/SUCCESS)
>    CGroup: /system.slice/ufw.service

This means ufw firewall is running, change the rule and let 403 go
`sudo ufw allow https`

Then everything works ok.

**Comment by jazzi** [comment]
By the way, when I run `pip -V` I got the following errors:

> Traceback (most recent call last):
>  File "D:\Python\lib\runpy.py", line 162, in _run_module_as_main
>   "__main__", fname, loader, pkg_name)
>  File "D:\Python\lib\runpy.py", line 72, in _run_code 
>   exec code in run_globals
>  File "D:\Python\Scripts\pip.exe\__main__.py", line 5, in <module>
> ImportError: cannot import name main

The bug is found in pip 10.0.0.

In linux you need to modify file: `vim /usr/bin/pip` from:

> from pip import main
> if __name__ == '__main__':
>     sys.exit(main())

to this:

> from pip import __main__
> if __name__ == '__main__':
>     sys.exit(__main__._main())
